shellcheck & cleanup

diff --git a/utils/zenity_project b/utils/zenity_project
--- a/utils/zenity_project
+++ b/utils/zenity_project
@@ -20,19 +20,35 @@
 # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-pack=${PROJECT_PACK:-$(dirname $(dirname $(readlink -f $0)))}
+pack="${PROJECT_PACK:-"$(dirname "$(dirname "$(readlink -f "$0")")")"}"
 test -d "$pack" || exit 1
 
-. $pack/bash_profile.sh
+. "$pack"/bash_profile.sh
 
 test -d "$PROJECTS_DIR" || exit 1
 
+shopt -s globstar nullglob
+
+fatal() {
+    echo "[1;32m**** $*[0m" >&2
+    exit 1
+}
+
 CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/zenity_project
-(
-    if test "`ls -dt $PROJECTS_DIR "$CACHE" 2> /dev/null | sed 1q`" != "$CACHE"; then
-        mkdir -p "`dirname "$CACHE"`" && ls $PROJECTS_DIR | sort -u > "$CACHE"
-    fi
-)
+CACHE_DIR=${CACHE%/*}
+
+cache-is-stale() {
+    for f in "$PROJECTS_DIR"/*; do
+        [[ "$f" -nt "$CACHE" ]] && return 0
+    done
+    return 1
+}
+
+# Test if the cache must be refreshed (i.e. there are newer files in $PROJECTS_DIR)
+if cache-is-stale; then
+    mkdir -p "$CACHE_DIR" || fatal "could not create '$CACHE_DIR' directory"
+    printf "%s\n" "$PROJECTS_DIR"/* | sort -u > "$CACHE"
+fi
 
 ask() {
     if [[ -x $(which yad 2>/dev/null) ]]; then
@@ -48,30 +64,32 @@ ask() {
 if project=$(ask); then
     if [ x"$project" != x ]; then
         PROFILE=$PROJECTS_DIR/$project/.zenity_profile
-        cat > $PROFILE <<EOF
+        cat > "$PROFILE" <<EOF
 set -p
-export PROJECT_PACK=$pack
+export PROJECT_PACK="$pack"
 
-if [ -e \$HOME/.bash_profile ]; then
-    . \$HOME/.bash_profile
-elif [ -e \$HOME/.profile ]; then
-    . \$HOME/.profile
-elif [ -e $HOME/.bashrc ]; then
-    . \$HOME/.bashrc
+if [ -e "\$HOME/.bash_profile" ]; then
+    . "\$HOME/.bash_profile"
+elif [ -e "\$HOME/.profile" ]; then
+    . "\$HOME/.profile"
+elif [ -e "$HOME/.bashrc" ]; then
+    . "\$HOME/.bashrc"
 fi
 if [ "\${PROJECT_CURRENT:-unknown}" = unknown ]; then
-    . \$PROJECT_PACK/bash_profile.sh
+    . "\$PROJECT_PACK"/bash_profile.sh
 fi
 _ssh_agent_check
-go_to_project $project
-at now -f <($pack/utils/run_emacs.sh) >/dev/null 2>&1 & disown
+go_to_project "$project"
+at now -f <("$pack"/utils/run_emacs.sh) >/dev/null 2>&1 & disown
 
 EOF
 
         if [[ -x $(which gnome-terminal 2>/dev/null) ]]; then
             exec gnome-terminal --geometry=132x50 --hide-menubar --command="bash --init-file $PROFILE"
         elif [[ -x $(which xterm 2>/dev/null) ]]; then
-            exec xterm +bc +cm -cr white -cu -en 'utf-8' -fa Inconsolata -fs 10 -j -ms white -rightbar +tb -rw -s -sb -si -sk -sl 4294967296 -sm -u8 -vb -wc +wf -w 4 -bd '#3f3f3f' -bg '#3f3f3f' -fg ivory -geometry 132x50 -n "Project: $project" -e bash --init-file $PROFILE
+            exec xterm \
+                 +bc +cm -cr white -cu -en 'utf-8' -fa Inconsolata -fs 10 -j -ms white -rightbar +tb -rw -s -sb -si -sk -sl 4294967296 -sm -u8 -vb -wc +wf -w 4 -bd '#3f3f3f' -bg '#3f3f3f' -fg ivory -geometry 132x50 \
+                 -n "Project: $project" -e bash --init-file "$PROFILE"
         else
             echo "No gnome-terminal nor xterm found" >&2
             exit 1
